### ISSUE TITLE
Add support for spritesheets?

### ISSUE THREAD

**Issue by spixi** [pyrollo/font_api#2]
I tried to write a mod for the unifont font, but it seems that minetest is unable to handle 65535 textures at the same time. It would be nice, if there was spritesheet support, at least for monospace fonts, so that only one bitmap texture has to be loaded into the memory instead of 65535. However, I don't know if the minetest engine has such a feature.

The mod generated by the following code lets the server run out of memory.

`````
#!/bin/bash

mkdir ~/.minetest/mods/font_unifont
cd ~/.minetest/mods/font_unifont

wget http://unifoundry.com/pub/unifont/unifont-11.0.02/unifont-11.0.02.bmp
# There is also unifont_upper-11.0.02.bmp which has the characters U+10000 to U+1FFFF.
# But at the moment we only support the Basic Multilingual Plane U+0000 to U+FFFF.

convert unifont-11.0.02.bmp -crop 4096x4096+32+64 +repage -crop 16x16 +repage +adjoin 'textures/font_unifont_%04x.png'

rm unifont_11.0.02.bmp

echo font_api > depends.txt

file="font_api.register_font('unifont',{margintop=2,linespacing=-2,height=16,widths={["
for i in {0..65534}; do file+=$i"]=16,["; done
file+="65535]=16}});"
echo $file > init.lua
`````

**Comment by pyrollo** [comment]
Hello,

The `[combine:` statement used to make the font texture does not offers any possibility to take an extract of an image. So spritesheet, that is actually a good idea for reducing texture number, is not implementable in font_api. You may open a issue on minetest engine for asking this evolution but I'm not sure this is that usefull.

Anyway 65536 chars is huge. Even if you use each char only once, it would take 30 full text pages to use them all. In what use case would you need so many chars ? Usually, a few hundreds is far enough to write in many languages.

**Comment by pyrollo** [comment]
No news , closing issue.
